import {
  MonitorSmartphone,
  Volume2,
  Mic,
  Camera,
  Zap,
  ToggleRight,
  Fingerprint,
  Battery,
  Wifi,
  Bluetooth,
  Smartphone,
  Cable,
  Keyboard,
  Mouse,
  Video,
  Speaker,
  Usb,
  MonitorCheck,
  Power,
  Headphones,
  Network,
  Fan,
  ScanFace,
  Watch,
  Activity,
  Circle,
  Hand,
  Monitor,
  Nfc,
  Wrench
} from "lucide-react";
import { LucideIcon } from "lucide-react";

export const checklistIcons: Record<string, LucideIcon> = {
  tela: MonitorSmartphone,
  alto_falante: Volume2,
  microfone: Mic,
  camera_frontal: Camera,
  camera_traseira: Camera,
  flash: Zap,
  botoes: ToggleRight,
  biometria: Fingerprint,
  touch_id: Fingerprint,
  face_id: ScanFace,
  desbloqueio_facial: ScanFace,
  bateria: Battery,
  wifi: Wifi,
  bluetooth: Bluetooth,
  chip: Smartphone,
  conectores: Cable,
  teclado: Keyboard,
  touchpad: Mouse,
  webcam: Video,
  alto_falantes: Speaker,
  portas_usb: Usb,
  porta_hdmi: Monitor,
  carregador: Cable,
  monitor: MonitorCheck,
  mouse: Mouse,
  fonte: Power,
  audio: Headphones,
  rede: Network,
  coolers: Fan,
  touch_bar: Keyboard,
  magsafe: Cable,
  thunderbolt: Zap,
  touch_id_teclado: Fingerprint,
  coroa_digital: Circle,
  sensores: Activity,
  pulseira: Watch,
  touch: Hand,
  nfc: Nfc,
  peca_trocada: Wrench
};
